# Generated by Django 4.0.2 on 2022-04-09 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partyroomreservation',
            old_name='day_of_use',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='tenniscourtreservation',
            old_name='use_time',
            new_name='date',
        ),
    ]
